name: linsticky
base: core24
version: '2.0.2'
summary: Lightweight and elegant sticky notes for your Linux desktop.
license: MIT
description: |
              LinSticky is a simple, modern, and lightweight sticky notes application designed for Linux. It provides a clean way to keep your reminders, tasks, and ideas right on your desktop.
              
              ✨ Key Features:
              📝 Smart Notes: A sleek, minimalist interface built with Python and GTK4 for maximum focus.
              🎨 Personalization: Organize your thoughts with a custom color palette.
              🌙 Night Theme: Full support for dark mode.
              ✍️ Formatting: Full support for rich text preservation (bold, italics, lists, change color and font size).
              🐧 Native Experience: Built with Libadwaita to look perfect on GNOME and other modern desktops.
              🌍 Multilingual: Fully localized in English, Español, Deutsch, Français, Русский, Қазақша, and more.
              
              If you are looking for a simple "post-it" style experience for Linux, LinSticky is the perfect tool for your daily workflow.

grade: stable
confinement: strict
icon: linsticky/resources/icons/app.png

parts:
  linsticky:
    plugin: python
    source: .
    stage-packages:
      - python3-gi
      - python3-cairo
      - gir1.2-adw-1
      - gir1.2-ayatanaappindicator3-0.1
    prime:
      - -build_deb_package.sh
      - -compile_translations.sh
      - -create_translation.sh
      - -generate_translations.sh
      - -update_translation.sh
      - -*.deb
      - -venv
      - -.git
      - -__pycache__
      - -.idea
      - -.venv
      - -pic
      - -stage
      - -overlay
      - -temp_mount
      - -linsticky_deb
      - -requirements.txt
      - -support.md
      - -README.md
      - -.gitignore
      - -LICENSE

    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/usr/bin
      if [ ! -f "$CRAFT_PRIME/usr/bin/python3" ]; then
        ln -s /usr/bin/python3 $CRAFT_PRIME/usr/bin/python3
      fi
      # Ensure the desktop file is copied to the correct location
      mkdir -p $CRAFT_PRIME/meta/gui
      cp $CRAFT_PART_SRC/snap/gui/io.linsticky.app.desktop $CRAFT_PRIME/meta/gui/
      cp $CRAFT_PART_SRC/snap/gui/app.png $CRAFT_PRIME/meta/gui/
      
      # Manually copy the source code to the expected location if the python plugin didn't do it as expected
      # This is a fallback to ensure the files are present
      mkdir -p $CRAFT_PRIME/lib/python3.12/site-packages/linsticky
      cp -r $CRAFT_PART_SRC/linsticky/* $CRAFT_PRIME/lib/python3.12/site-packages/linsticky/
      
      # Also copy the config and resources directories if they are outside the linsticky package
      # Based on the project structure, they seem to be inside, but let's be safe
      if [ -d "$CRAFT_PART_SRC/config" ]; then
          mkdir -p $CRAFT_PRIME/lib/python3.12/site-packages/config
          cp -r $CRAFT_PART_SRC/config/* $CRAFT_PRIME/lib/python3.12/site-packages/config/
      fi

slots:
  dbus-linsticky:
    interface: dbus
    bus: session
    name: io.linsticky.app

apps:
  linsticky:
    command: bin/python3 $SNAP/lib/python3.12/site-packages/linsticky/main.py
    desktop: meta/gui/io.linsticky.app.desktop
    extensions:
      - gnome
    common-id: io.linsticky.app
    slots:
      - dbus-linsticky
    plugs:
      - home
      - unity7
      - gsettings
      - network
      - wayland
      - x11
